apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 35.221.47.235
  ports:
  - port: 80 
    protocol: TCP 
    targetPort: 80
  selector:                
    app: frontend