apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  type: LoadBalancer
  loadBalancerIP: 34.145.245.86
  ports:
    - name: webui
      protocol: TCP
      port: 9870
      targetPort: 9870
    - name: fs
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: namenode
